Download Latin.unicharset along with radical-stroke.txt
tesseract-ocr/tesstrain pull request #219
Opened 2020-12-17 16:09 UTC by Shreeshrii

Need another PR to add Inherited.unicharset after https://github.com/tesseract-ocr/langdata_lstm/pull/41/ is merged

2020-12-17 16:23 UTC, kba approved these changes

2020-12-17 16:46 UTC, stweil commented
All unicharset files for scripts are potentially needed, starting with `Arabic.unicharset` and ending with `Thai.unicharset`.

I usually get the required ones to satisfy the error message(s), but still don't know what happens if they are missing.

2020-12-18 07:15 UTC, Shreeshrii commented
I added only Latin and Inherited unicharsets in this list because these are required in almost all cases, even though they don't stop processing like missing radical-stroke.txt.

We could add another optional variable for SCRIPT_UNICHARSET, downloading it when it is non-blank.

>still don't know what happens if they are missing.

I think some characters e.g. Arabic accents get dropped in the generated unicharset by unicharset_extractor.  That was the reason I built the Inherited.unicharset.

2021-01-14 19:30 UTC, stweil requested changes

2021-01-14 19:37 UTC, stweil commented
A list of all required `unicharset` files can be extracted from `unicharset`:

    cat $(OUTPUT_DIR)/unicharset | sed s/.*0,0,0.// | sed 's/ .*//' | sort | uniq | grep "^[A-Z][a-z][a-z]*" | grep -v common

2021-01-15 04:20 UTC, Shreeshrii commented on Makefile
> +	wget -O $(DATA_DIR)/Latin.unicharset 'https://github.com/tesseract-ocr/langdata_lstm/raw/master/Latin.unicharset'
Inherited.unicharset is NOT there in langdata_lstm repo. I created it by copying the lines with Inherited from other unicharsets. But there are some differences in coordinates for same character in different unicharsets, so I am not sure which one is to be used.

2021-01-15 18:10 UTC, Shreeshrii commented
Thanks for the suggestions @stweil and the hint to get the list of required unicharsets from  $(OUTPUT_DIR)/unicharset. 

I am having a hard time putting it together in a separate Makefile target using the list. Would appreciate if you can make the required change.

2021-01-22 08:21 UTC, wrznr commented
@kba Could you pls. have a look at the change request and maybe come up with a proposal?

2021-01-22 12:59 UTC, Shreeshrii commented
I added ` sed '/Common/d' | sed '/Inherited/d' | sed '/Joined/d'` to the script suggested by @stweil because there are no unicharsets for Common and Inherited . Joined was being picked up accidentally.

A simpler way maybe asking the user to specify a script and download that.

2021-01-29 15:51 UTC, Shreeshrii commented
>A simpler way maybe asking the user to specify a script and download that.

I have tried that in the new [Makefile-font2model](https://github.com/tesseract-ocr/tesstrain/blob/1466135f0ec673ec5cb25385d76241de24058511/Makefile-font2model#L205-L213)
I think that is a much cleaner way of doing this.

2021-02-02 16:25 UTC, Shreeshrii commented
Included as part of https://github.com/tesseract-ocr/tesstrain/pull/230

2021-02-02 16:25 UTC, closed without merging

2021-05-23 15:03 UTC, typeoo commented on Makefile
> +	wget -O $(DATA_DIR)/Latin.unicharset 'https://github.com/tesseract-ocr/langdata_lstm/raw/master/Latin.unicharset'
Hi 
how can I get the **Inherited.unicharset**